# Car Price Prediction using Machine Learning

In [77]:
import pandas as pd
import numpy as np

In [78]:
dataset = pd.read_csv("quikr_car_dataset.csv")

dataset.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [79]:
dataset.shape

(892, 6)

In [80]:
dataset.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='object')

In [81]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [82]:
dataset.describe()

              name company  year          Price  kms_driven fuel_type
count          892     892   892            892         840       837
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            13     235   117             35          30       440

In [83]:
dataset['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [84]:
dataset['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [85]:
dataset['company'].unique()

array(['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'I', 'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Commercial', 'MARUTI', 'Force', 'Mercedes', 'Land', 'Yamaha',
       'selling', 'URJENT', 'Swift', 'Used', 'Jaguar', 'Jeep', 'tata',
       'Sale', 'very', 'Volvo', 'i', '2012', 'Well', 'all', '7', '9',
       'scratch', 'urgent', 'sell', 'TATA', 'Any', 'Tara'], dtype=object)

# Cleaning the dataset

In [86]:
df = dataset.copy()

In [87]:
# removing non numeric year from year column

dataset = dataset[dataset['year'].str.isnumeric()]

In [88]:
# changing the year column to integer

dataset['year'] = dataset['year'].astype(int)

<ipython-input-88-ffcc15c92b38>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['year'] = dataset['year'].astype(int)

In [89]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int64
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.0+ KB

In [90]:
dataset.shape

(842, 6)

In [91]:
# counting the 'ask for price' columns

dataset[dataset['Price'] == 'Ask For Price'].count()

name          23
company       23
year          23
Price         23
kms_driven    21
fuel_type     21
dtype: int64

In [92]:
# removing ask for price from price column

dataset = dataset[dataset['Price'] != 'Ask For Price']

In [93]:
dataset.shape

(819, 6)

In [94]:
# removing commas from price column

dataset['Price'] = dataset['Price'].str.replace(',', '').astype(int)

In [95]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [96]:
dataset.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,"36,000 kms",Diesel
6,Ford Figo,Ford,2012,175000,"41,000 kms",Diesel

In [97]:
# removing , and kms and spaces

dataset['kms_driven'] = dataset['kms_driven'].str.split(' ').str.get(0).str.replace(',', '')
dataset['kms_driven'].unique()

array(['45000', '40', '28000', '36000', '41000', '25000', '24530',
       '60000', '30000', '32000', '48660', '4000', '16934', '43000',
       '35550', '39522', '39000', '55000', '72000', '15975', '70000',
       '23452', '35522', '48508', '15487', '82000', '20000', '68000',
       '38000', '27000', '33000', '46000', '16000', '47000', '35000',
       '30874', '15000', '29685', '130000', '19000', '54000', '13000',
       '38200', '22000', '50000', '13500', '3600', '45863', '60500',
       '12500', '18000', '13349', '29000', '44000', '42000', '14000',
       '49000', '36200', '51000', '104000', '33333', '33600', '5600',
       '7500', '26000', '24330', '65480', '200000', '59000', '99000',
       '2800', '21000', '11000', '66000', '3000', '7000', '38500',
       '37200', '43200', '24800', '45872', '40000', '11400', '97200',
       '52000', '31000', '175430', '37000', '65000', '3350', '75000',
       '62000', '73000', '2200', '54870', '34580', '97000', '60', '80200',
       '3200', '0000', '5000', '588', '71200', '175400', '9300', '56758',
       '10000', '56450', '56000', '32700', '9000', '73', '160000',
       '58559', '57000', '170000', '80000', '6821', '23000', '34000',
       '1800', '400000', '48000', '90000', '12000', '69900', '166000',
       '122', '0', '36469', '7800', '24695', '15141', '59910', '100000',
       '4500', '129000', '300', '131000', '111111', '59466', '25500',
       '44005', '2110', '43222', '100200', '65', '140000', '103553',
       '58000', '120000', '49800', '100', '81876', '6020', '55700',
       '18500', '53000', '35500', '22134', '1000', '8500', '87000',
       '6000', '8000', '55800', '56400', '72160', '11500', '133000',
       '2000', '88000', '65422', '117000', '150000', '10750', '6800',
       '9800', '57923', '30201', '6200', '37518', '24652', '383', '95000',
       '3528', '52500', '47900', '52800', '195000', '48008', '48247',
       '9400', '64000', '2137', '10544', '147000', '90001', '48006',
       '74000', '85000', '29500', '39700', '67000', '19336', '60105',
       '45933', '102563', '28600', '41800', '116000', '42590', '7400',
       '54500', '76000', '00', '11523', '38600', '95500', '37458',
       '85960', '12516', '30600', '2550', '62500', '69000', '28400',
       '68485', '3500', '85455', '63000', '1600', '77000', '26500',
       '2875', '13900', '1500', '2450', '1625', '33400', '60123',
       '137495', '91200', '146000', '100800', '2100', '2500', '132000',
       'Petrol'], dtype=object)

In [98]:
dataset = dataset[dataset['kms_driven'].str.isnumeric()]

In [99]:
dataset.shape

(817, 6)

In [100]:
dataset['kms_driven'] = dataset['kms_driven'].astype(int)

<ipython-input-100-11edc8e8f43e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['kms_driven'] = dataset['kms_driven'].astype(int)

In [101]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

In [102]:
dataset  = dataset[~dataset['fuel_type'].isna()]

In [103]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.6+ KB

In [104]:
# dataset['name'] = dataset['name'].str.split(' ').str.slice(0,3).str.join(' ')
dataset['name']=dataset['name'].str.split().str.slice(start=0,stop=3).str.join(' ')

In [105]:
# dataset['name'] = dataset['name'].str.split(' ').str.slice(0,3)

In [106]:
dataset.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6               Ford Figo      Ford  2012  175000       41000    Diesel

In [107]:
dataset = dataset.reset_index(drop = True)

In [108]:
dataset

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [109]:
# dataset = dataset.drop('Price', axis = 1)

In [110]:
dataset.head(10)

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel
5             Hyundai Eon   Hyundai  2013  190000       25000    Petrol
6  Ford EcoSport Ambiente      Ford  2016  830000       24530    Diesel
7      Maruti Suzuki Alto    Maruti  2015  250000       60000    Petrol
8     Skoda Fabia Classic     Skoda  2010  182000       60000    Petrol
9  Maruti Suzuki Stingray    Maruti  2015  315000       30000    Petrol

In [111]:
dataset.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [112]:
dataset = dataset[dataset['Price']<6e6].reset_index(drop = True)

In [113]:
dataset.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [114]:
dataset

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [115]:
# creating a csv file and saving it

dataset.to_csv('cleaned_car_dataset.csv')

## Splitting Features and Target columns

In [116]:
X = dataset.drop(columns = 'Price')
y = dataset['Price']

In [117]:
X.head()

                     name   company  year  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2       Hyundai Grand i10   Hyundai  2014       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014       36000    Diesel
4               Ford Figo      Ford  2012       41000    Diesel

In [118]:
y.head()

0     80000
1    425000
2    325000
3    575000
4    175000
Name: Price, dtype: int64

In [137]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [138]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose  import make_column_transformer
from sklearn.pipeline import make_pipeline

In [139]:
ohe = OneHotEncoder()
ohe.fit(X[['name', 'company', 'fuel_type']])

OneHotEncoder()

In [140]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [141]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_), ['name', 'company', 'fuel_type']), remainder = 'passthrough')

In [142]:
lr = LinearRegression()

In [143]:
pipe = make_pipeline(column_trans, lr)

In [144]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [145]:
y_pred = pipe.predict(X_test)

In [146]:
r2_score(y_test, y_pred)

0.7239646424103914

In [147]:
scores=[]

for i in range(1000):
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= i)
  lr = LinearRegression()
  pipe = make_pipeline(column_trans, lr)
  pipe.fit(X_train, y_train)
  y_pred = pipe.predict(X_test)
  print(r2_score(y_test, y_pred), i)
  scores.append(r2_score(y_test, y_pred))

0.659028389313812 0
0.4786019553698676 1
0.6207794249081153 2
0.5370191770781386 3
0.8188957905376869 4
0.6635817972380802 5
0.6276610482734784 6
0.658886944877979 7
0.6720870702301194 8
0.5700289166177432 9
0.648400695064776 10
0.6085893532390639 11
0.45711028776282436 12
0.6674682027197638 13
0.5613097872692655 14
0.6302127178342503 15
0.4878885663268868 16
0.6657802384033991 17
0.6089260020595317 18
0.6080562969876123 19
0.6411124833470485 20
0.6211086834306807 21
0.7365259405794765 22
0.653994542608233 23
0.5492516137612884 24
0.4986871836018081 25
0.6732800830731375 26
0.7035649246277966 27
0.7254724384008826 28
0.600910758620459 29
0.6245216809266249 30
0.6307771095375861 31
0.7684179661400119 32
0.7854181846967916 33
0.5622406009154048 34
0.6843880928625425 35
0.5778501283957556 36
0.6170935895719769 37
0.5392533652542745 38
0.7163902856790179 39
0.33482488133690524 40
0.6733566469697455 41
0.573149277112929 42
0.6792286429339746 43
0.6604143324086663 44
0.6974514018128077 45
0.525862327771285 46
0.5882048173860872 47
0.7540195112572856 48
0.6861718088978235 49
0.5037872879767833 50
0.586812688836341 51
0.632522789353089 52
0.6638926836558409 53
0.589112989894671 54
0.7179472103151312 55
0.717175568098208 56
0.7195108580236478 57
0.7268820093703969 58
0.4842761005742361 59
0.5849507096737491 60
0.5244538018772709 61
0.433039200149794 62
0.6189094499304117 63
0.607523587256112 64
0.6416062192499459 65
0.4811447223848906 66
0.6590401360294219 67
0.6214516740855269 68
0.7354748082088625 69
0.6997028216680148 70
0.7184868571550431 71
0.5796711877011372 72
0.6844489175315828 73
0.551793320583463 74
0.5834752739344502 75
0.4493032495838605 76
0.6079689454365631 77
0.5738544674121827 78
0.6460657581622671 79
0.577823269354524 80
0.6159045102900031 81
0.6859165377679719 82
0.743384407606746 83
0.6733483462787853 84
0.6358946187880978 85
0.6852016924795135 86
0.5372719991799653 87
0.6190974484848143 88
0.6384276586522919 89
0.6810906331327519 90
0.5855129047832761 91
0.6883538417762367 92
0.49449942493848387 93
0.6330568416218234 94
0.6552946174673371 95
0.6359146937063267 96
0.6856429333792444 97
0.6751126666458885 98
0.6016909511218049 99
0.6899511439779622 100
0.6600548233403788 101
0.6837503672381984 102
0.5929485901619975 103
0.7041146875653272 104
0.5649570265941317 105
0.6078514486006589 106
0.5763911737120335 107
0.5851255973613092 108
0.7107004246730105 109
0.6767095983739779 110
0.6662479194313271 111
0.4423022721705616 112
0.6956021024757175 113
0.7099506032148144 114
0.5689669381027651 115
0.5902811367648474 116
0.652570682810167 117
0.5318109113302302 118
0.7325366971557827 119
0.6582210770656937 120
0.595325160920579 121
0.7077950470408351 122
0.6260915849841364 123
0.8216111047306386 124
0.6810050373204938 125
0.6376718924575715 126
0.6239450939828749 127
0.5828209340389368 128
0.5503845109971282 129
0.6062883548958968 130
0.5053332997506421 131
0.6594883488762618 132
0.5821833399036935 133
0.7027442684204902 134
0.7148724201115054 135
0.5440227636089932 136
0.7129101331739802 137
0.6644601306165266 138
0.5592359030451852 139
0.7181200738715663 140
0.586707292634035 141
0.6612070185139789 142
0.692837218979131 143
0.6285984495688126 144
0.5545724939778711 145
0.6359351690027988 146
0.6172447730316644 147
0.5635045247731529 148
0.6341816693284106 149
0.627743883541668 150
0.772457633797212 151
0.5656313186612019 152
0.5011881507237921 153
0.6341541976471358 154
0.6589044156174964 155
0.41279506168753166 156
0.7311839662116084 157
0.6253658805653508 158
0.6780703704660516 159
0.6462571754903585 160
0.5930433384473763 161
0.6643181371826166 162
0.5706313032195947 163
0.5745007174299005 164
0.6902995180218212 165
0.6527340794975962 166
0.4648361771300483 167
0.5687424839939058 168
0.6962495500293869 169
0.6917454801131311 170
0.6498239833010879 171
0.8245123213324895 172
0.718992040565873 173
0.5446508704072239 174
0.6143157269164068 175
0.6727430243354923 176
0.6113005131281295 177
0.7143355770247861 178
0.6795838296854038 179
0.6414188326428321 180
0.6169824287858405 181
0.6744886457790076 182
0.638985519283307 183
0.5049585197682431 184
0.666849890554815 185
0.7358390399884635 186
0.6531625898525524 187
0.6973299080330215 188
0.5960796801052973 189
0.7116342252143624 190
0.6649212724129587 191
0.5791597078743078 192
0.6911304269008782 193
0.7293193172236787 194
0.6272050857852782 195
0.6319631110325659 196
0.7493872677173319 197
0.4023084580055102 198
0.7100721813965516 199
0.7119531728817382 200
0.4515508202674908 201
0.6158239721231967 202
0.7847877660491328 203
0.5827883999385441 204
0.6723154025725522 205
0.7711375970627736 206
0.5818236565054682 207
0.6767066093265912 208
0.30045107228791 209
0.49258961567591664 210
0.509741774433156 211
0.5691038036186032 212
0.6186552639301196 213
0.6760565300579161 214
0.6227908253965908 215
0.5303560047071902 216
0.6022692538337369 217
0.5417954331241707 218
0.5634461146360645 219
0.590530600965717 220
0.6818290366611587 221
0.4753900792365974 222
0.49586210928825436 223
0.5517164158982745 224
0.7244696860939759 225
0.7405893047191298 226
0.6279635640505846 227
0.7309082912898718 228
0.5825795419803659 229
0.5539204462348989 230
0.5950645077087391 231
0.6308003186058262 232
0.44063405590122906 233
0.7244616613844641 234
0.5867152542101468 235
0.6663298402592914 236
0.6089742734947662 237
0.5300946851733747 238
0.5940300612312339 239
0.5705668175735403 240
0.48454217372528874 241
0.5400401893829667 242
0.6399324145962523 243
0.4958581977803346 244
0.7819359491968757 245
0.7796864457099157 246
0.7463107508321959 247
0.7800635258929455 248
0.5431780102434498 249
0.607067638317368 250
0.5083846978209237 251
0.5594161966989665 252
0.6510086889568631 253
0.5879781394400327 254
0.7699647575711044 255
0.5590631009040427 256
0.6989303095571331 257
0.6482701366042968 258
0.5645011225972072 259
0.715414420909389 260
0.7589220962500574 261
0.7047736774214215 262
0.7668959407006899 263
0.6347478537740667 264
0.6282154776894424 265
0.6503164564985624 266
0.6530177908365441 267
0.4747537676713278 268
0.5469399073302446 269
0.627244974392916 270
0.549419792004114 271
0.6221084248719211 272
0.6177832358460331 273
0.7136907653855701 274
0.6135681956578162 275
0.7534337689806304 276
0.6969618411590603 277
0.6287172968756725 278
0.7884313944707013 279
0.6557660005582244 280
0.6544749232394982 281
0.6888963908193559 282
0.7344573369425631 283
0.7173743442902537 284
0.5663908107713629 285
0.7224584859866565 286
0.5928054944688351 287
0.4684830093577157 288
0.45184706994699664 289
0.5200021260717484 290
0.6900129585235288 291
0.5407547607465958 292
0.7512168644233137 293
0.8131943030426345 294
0.6309712308600188 295
0.7431132179580244 296
0.7010385458143538 297
0.5330075263108845 298
0.7082208291201753 299
0.7690409215335718 300
0.6807209760622919 301
0.7634623096918358 302
0.4872235239216949 303
0.6453000383381734 304
0.5920287737124548 305
0.7821052680408945 306
0.6918234963834177 307
0.6490729008560034 308
0.6969546046789101 309
0.6748489100785835 310
0.6069499719896703 311
0.5106339751538544 312
0.4994403334974219 313
0.5452521323067663 314
0.7374758228041618 315
0.5830981567847356 316
0.6074497164269506 317
0.6538698035325743 318
0.5117568827529202 319
0.47565664405144403 320
0.5894967130157149 321
0.5330965491306714 322
0.5698312299455881 323
0.6196766632373736 324
0.5365184791166464 325
0.5927246398691179 326
0.7233059790357781 327
0.6937591044309651 328
0.5143585793897609 329
0.6496400551781494 330
0.5010393038860071 331
0.6155762225378807 332
0.5731374443107017 333
0.6979812142246836 334
0.6015680735297482 335
0.5098609707026592 336
0.6709629027939128 337
0.6187094440221905 338
0.5307522702581402 339
0.7413398675456236 340
0.7319033890348289 341
0.5999509998828565 342
0.6714114201812711 343
0.6914958747039833 344
0.6448765913388187 345
0.6674152371498947 346
0.5894650532860114 347
0.7064416466570889 348
0.6225830024292502 349
0.7436127498779607 350
0.7073784247944652 351
0.5742433731456462 352
0.4602676226419514 353
0.7286266879098448 354
0.6677842159888883 355
0.6984702091995867 356
0.6470049676367038 357
0.7076077658416036 358
0.5834341391368818 359
0.7067845931266293 360
0.6771982566560352 361
0.5386166765609898 362
0.6993036618445954 363
0.7148348473474011 364
0.5634043926953246 365
0.6905045866124062 366
0.44471194058976726 367
0.7161274372396015 368
0.7338589974590972 369
0.6938623102178886 370
0.6248975023298455 371
0.6434802702900618 372
0.6744899064601821 373
0.518664409676794 374
0.5618168103636201 375
0.6845721543978824 376
0.6172818185696589 377
0.7351715751508225 378
0.7702641752127355 379
0.6491662298886118 380
0.6923022453673038 381
0.7054188562055794 382
0.8071049117104462 383
0.6887684036743976 384
0.7046993380817521 385
0.6714744570991205 386
0.6029499296485759 387
0.5647628195074039 388
0.43428864403456324 389
0.7343331002965126 390
0.562183870316636 391
0.8082332720164357 392
0.3785549101154331 393
0.6367678238986789 394
0.7001969890045029 395
0.5506427337335992 396
0.594139032946245 397
0.7002839795926565 398
0.7082988189333999 399
0.649337692891315 400
0.5867807763621969 401
0.5587583621654244 402
0.497668783415397 403
0.5773171759755202 404
0.57764593656462 405
0.574503969921687 406
0.624502730590125 407
0.7033489261614829 408
0.6685916987667412 409
0.686052043727092 410
0.6551744315743546 411
0.6483890864373151 412
0.5173805259067792 413
0.5839991003272034 414
0.5401975094482377 415
0.47032169556458725 416
0.692820326373035 417
0.6768367908497861 418
0.6701708319381401 419
0.7179600059550493 420
0.6518958570955724 421
0.688690935012801 422
0.6501063202741688 423
0.6281535637617854 424
0.5793855829317012 425
0.43456250556084086 426
0.7365610680447343 427
0.5300750277111625 428
0.6585948837456366 429
0.6815809811671266 430
0.7746236624035746 431
0.6477681072775094 432
0.8456515104452564 433
0.6046984466234515 434
0.7763336443263222 435
0.5835017807437324 436
0.7060657264604637 437
0.6329019492207983 438
0.7038857938212839 439
0.6412360934164225 440
0.670766616966971 441
0.5887428928360793 442
0.8022179978938284 443
0.7720550197904045 444
0.7427621011208936 445
0.721533859842068 446
0.6596647230270529 447
0.5661453144093886 448
0.7531613495504904 449
0.7765011355934265 450
0.5497127533385873 451
0.5774507434415898 452
0.6333068542413034 453
0.7082439249656362 454
0.6403512324041725 455
0.4955709323486337 456
0.513276163137355 457
0.7296128633728534 458
0.6464413432288583 459
0.7460914445791844 460
0.5490151711082758 461
0.5891795824428256 462
0.7732998672448623 463
0.5183983206818822 464
0.6222064888390684 465
0.6802269369825149 466
0.5990840836173427 467
0.6848505802552778 468
0.6499012630241231 469
0.49057441899274834 470
0.5428393092657704 471
0.35083170952117093 472
0.6722658451483381 473
0.7031297380479582 474
0.7606882333208262 475
0.6048437886507256 476
0.6266673945651073 477
0.7329140047321591 478
0.534253051426339 479
0.5465295694148691 480
0.6002398349174307 481
0.609251603095756 482
0.5348871284288783 483
0.5552946164168533 484
0.5178163298773851 485
0.6340270973119808 486
0.5806142095295552 487
0.739981480443012 488
0.6327497582043735 489
0.5089920596013391 490
0.7762555869304931 491
0.6032387736812563 492
0.6162241740439061 493
0.6711226435921567 494
0.5491444164493058 495
0.7011695455761137 496
0.6497480460876048 497
0.6638832738997072 498
0.7795835566594276 499
0.6826755836372029 500
0.6049609552895732 501
0.5606383429788726 502
0.6312327525367749 503
0.5073076534289633 504
0.6690233884551787 505
0.6966013395324483 506
0.7637322773222588 507
0.687312287135897 508
0.6534974574119365 509
0.6378217969673738 510
0.6187186729052853 511
0.6376774547300326 512
0.7256449393769164 513
0.6603301229542757 514
0.7835902417604856 515
0.7193480892162991 516
0.759086487488061 517
0.5945146271244762 518
0.6750971899563668 519
0.6941294503495772 520
0.684692489752141 521
0.49792892792679777 522
0.5697480771252805 523
0.5324658862587737 524
0.47164858524739506 525
0.6351965155049775 526
0.6889808701352746 527
0.7635494660451237 528
0.6536169239891092 529
0.6277302016385654 530
0.5634747387128756 531
0.6366652637731988 532
0.737647189641647 533
0.5088199121376692 534
0.5794384247892379 535
0.6378429310629614 536
0.5298643004681127 537
0.6777510443409309 538
0.5758290713576177 539
0.6923967227497927 540
0.6007347783346737 541
0.6790223053208762 542
0.5830547097512813 543
0.6958763308629108 544
0.46341376877101026 545
0.7139680930300423 546
0.3235473610457128 547
0.7312975727266423 548
0.5020649148083915 549
0.6214065033217533 550
0.6739217045971891 551
0.5926594933485076 552
0.7245073070264563 553
0.6318063574094861 554
0.7147748552376642 555
0.5554050721058345 556
0.5144547960107496 557
0.6955438031004203 558
0.7086436720322673 559
0.6142662794883009 560
0.4906697970313033 561
0.7054084664358049 562
0.5894627051323837 563
0.6573804897265703 564
0.674515673035138 565
0.7941490660068025 566
0.7144605816494289 567
0.7270502954078857 568
0.6182406685211249 569
0.6403062171228528 570
0.6472243815357688 571
0.6797340679556936 572
0.6243748099365708 573
0.5746213448281481 574
0.694827215167675 575
0.6784430637345497 576
0.7611204434353909 577
0.6667073894567086 578
0.6317921121530068 579
0.593325486849748 580
0.6461056631930379 581
0.49716080517682393 582
0.5845087295778784 583
0.5219645709285398 584
0.5789592388768561 585
0.6937897951304324 586
0.6385352532970103 587
0.7001040245345016 588
0.6931513772693663 589
0.5895977617928446 590
0.6973419866646663 591
0.7228921696807253 592
0.7177833396359936 593
0.6371743878636229 594
0.3874877617936837 595
0.5581488661288566 596
0.5620076746883371 597
0.5642921939190522 598
0.5257542955235854 599
0.5192376555117657 600
0.5706306400269022 601
0.711153890502749 602
0.5858278201750718 603
0.5442014860603344 604
0.7491487433581316 605
0.48604251030626433 606
0.6077067582339021 607
0.6830914054092725 608
0.5955848987865537 609
0.47379652169838005 610
0.5961593778059873 611
0.6070377608546855 612
0.5992158389656232 613
0.6678934543818701 614
0.5918228625365761 615
0.37126699601597757 616
0.5820805213641518 617
0.6802513300187689 618
0.6069350542754416 619
0.5097428544282452 620
0.7211530301064157 621
0.602955725043241 622
0.5126777225092629 623
0.76226174966682 624
0.6371921727740009 625
0.6938113673603201 626
0.5128777473759297 627
0.6716511134587118 628
0.6444036550637287 629
0.5865324482487522 630
0.7593972844258333 631
0.68048888292765 632
0.6366473217148794 633
0.5160353494143639 634
0.5842652459511208 635
0.6789581364682236 636
0.7054307955226712 637
0.7503125356029614 638
0.5432995087954455 639
0.5651112541518637 640
0.6711280780617683 641
0.6808804463234643 642
0.6024193488490824 643
0.48495715163410447 644
0.6935376415168037 645
0.5975463263807363 646
0.422040572582031 647
0.604064517884908 648
0.6484605754319818 649
0.672334722083183 650
0.5874672814578117 651
0.7503700202331405 652
0.7507424523983272 653
0.6501819204765705 654
0.6499164289064727 655
0.5854742704633928 656
0.4606221087240516 657
0.675282901851195 658
0.6647053988633171 659
0.7253781042903418 660
0.7687315589885062 661
0.55861632486695 662
0.5151362172476767 663
0.47995193101168576 664
0.6709825497893235 665
0.6207791721076183 666
0.6989357112987891 667
0.7160597237938806 668
0.7371402404331412 669
0.750338216654125 670
0.5248797605310955 671
0.6650602322323769 672
0.7328779397012857 673
0.6646606193531287 674
0.6287176741963832 675
0.6620485462371175 676
0.5649447299215948 677
0.7115552713325233 678
0.6584709793569198 679
0.6187387019606293 680
0.5215743357602347 681
0.7208037577114383 682
0.6986316126485483 683
0.5872970788987246 684
0.621932702088938 685
0.8313722155875224 686
0.6330784207947512 687
0.5546605879993038 688
0.7931812927003842 689
0.602504220579906 690
0.6814876517009929 691
0.6118213149341658 692
0.6541429134305854 693
0.6920131513286434 694
0.7115325887699382 695
0.6608543916803803 696
0.5533643138881866 697
0.7515394004006034 698
0.6663198388264797 699
0.47695603875949777 700
0.7039532808030218 701
0.5967327444289509 702
0.7294048028069887 703
0.5353691063650219 704
0.6827157347720891 705
0.7312497284666382 706
0.6604285515947435 707
0.654955167919588 708
0.5332442801761221 709
0.6449395302268014 710
0.7112236301992062 711
0.8112929555664737 712
0.7290807057968062 713
0.6573265811899788 714
0.6778602942086787 715
0.7205762769260822 716
0.7319366769466142 717
0.34217467260851353 718
0.6459372648403187 719
0.5516974435694972 720
0.5873830332609322 721
0.6768894725776151 722
0.6791947757288436 723
0.6546338621987936 724
0.6220052902211166 725
0.6519528641868584 726
0.6891649002232082 727
0.6081079473862293 728
0.5800311805973106 729
0.7256150400611057 730
0.5286038286777643 731
0.7940023976824027 732
0.671973305639906 733
0.5889136346001067 734
0.545566420032233 735
0.6129836465140948 736
0.5105303535427053 737
0.7133972467397816 738
0.5987686136235477 739
0.6147237505089025 740
0.5937412391040855 741
0.7512051843263232 742
0.756556177410123 743
0.592901933921428 744
0.6130968595171196 745
0.660376936962723 746
0.5529868265692585 747
0.5925912738823236 748
0.5104398616635255 749
0.5548357916908799 750
0.7058752538391131 751
0.7641198129896389 752
0.6888812935317339 753
0.7142415036516969 754
0.652040880690494 755
0.6011933655444324 756
0.7514728270562887 757
0.5946098199508378 758
0.6332055676871245 759
0.6652462362349045 760
0.6658762373975016 761
0.7120079234447385 762
0.6430703798451315 763
0.6178812922169499 764
0.6603787706016705 765
0.6258221774356405 766
0.6269536918056571 767
0.5344639431483975 768
0.7578402524370281 769
0.6716696452124649 770
0.6976838430843504 771
0.7030790620555437 772
0.6080612880469893 773
0.5576711873789987 774
0.5851138637888698 775
0.5555056043259607 776
0.38852411320956204 777
0.7044396378347393 778
0.6546885267281652 779
0.6546584179462446 780
0.824745861065094 781
0.7102046122976793 782
0.7833892989632312 783
0.6411165609966064 784
0.634194692162967 785
0.6375187990718215 786
0.6561277439292283 787
0.6974690390784719 788
0.4497324824644946 789
0.7190351327708597 790
0.7028766008140369 791
0.7349460657143989 792
0.7383346596719915 793
0.6578211515769228 794
0.5603754955422047 795
0.73428310698107 796
0.6066255215670804 797
0.6343947325947082 798
0.7477939728118864 799
0.6284221345506555 800
0.5092167434916228 801
0.613117327507762 802
0.6533098402979136 803
0.5457427423190104 804
0.5977229059559347 805
0.6455129789655465 806
0.7459992237350623 807
0.3888213035816743 808
0.5655152995148705 809
0.5549830908346258 810
0.6486159324542742 811
0.6613012207049529 812
0.5258705274976964 813
0.7881359239542052 814
0.6277596558462282 815
0.5990465599136795 816
0.7028523180314639 817
0.656867973273418 818
0.653476116279571 819
0.5587652773793109 820
0.7774203916466214 821
0.6599149752874244 822
0.5951125531797912 823
0.44789344006297416 824
0.7185944747061491 825
0.6643153005842564 826
0.7601264825114996 827
0.6538724926158557 828
0.6380374952206549 829
0.49085440025858074 830
0.7088806893933592 831
0.775243279695109 832
0.5774197969206302 833
0.7125575392221659 834
0.6402513160627519 835
0.5731077234969326 836
0.6388388433226397 837
0.6208526831459737 838
0.594740494358696 839
0.7293355445878011 840
0.7584071886591763 841
0.7251549868061127 842
0.7080531392953822 843
0.6734722138669708 844
0.49470912942149514 845
0.6089783956648982 846
0.6132553159203233 847
0.575124621133505 848
0.6889109888094773 849
0.727929705366319 850
0.6004283994971509 851
0.6351298549083431 852
0.6576931348593089 853
0.5506713180161427 854
0.6308099098506665 855
0.5421421652329707 856
0.502337672606138 857
0.764318474958035 858
0.525702890674933 859
0.7757681273196243 860
0.5755166685646295 861
0.6675332447927602 862
0.5780706055487512 863
0.6717905680741172 864
0.5563259336377573 865
0.6233980230311771 866
0.602388701609775 867
0.5554463341115639 868
0.6471105906416674 869
0.5748861154797391 870
0.5102116887444537 871
0.6686442220920792 872
0.6209498641700109 873
0.6865250205239881 874
0.6563741694945461 875
0.6480367689851765 876

In [148]:
np.argmax(scores)

433

In [149]:
scores[np.argmax(scores)]

0.8456515104452564

In [150]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test, y_pred))
scores.append(r2_score(y_test, y_pred))

0.8456515104452564

## Saving the model

In [151]:
import pickle

In [152]:
pickle.dump(pipe, open('LinearRegressionModel.pkl', 'wb'))

## Prediction

In [153]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti', 2019, 100, 'Petrol']], columns = ['name', 'company', 'year', 'kms_driven', 'fuel_type']))

array([459113.49353657])